---
abstract: 'Perl port of Wappalyzer (L<http://wappalyzer.com>)'
author:
  - 'Alexander Nalobin <alexander@nalobin.ru>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Wappalyzer
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 0
  JSON: 0
  Test::More: 0
  lib::abs: 0
version: 0.04
